### ISSUE TITLE
Radio with custom integer values is not graded properly on correct answer

### ISSUE THREAD

**Issue by MikaelSiidorow** [apluslms/mooc-grader#135]
If I have a submit exercise with a radio field:
```yaml
# -- snip --
max_points: 1
view_type: access.types.stdsync.createForm

fieldgroups:
  - title: Radio Form
    type: radio
    required: true
    points: 1
    options:
      - label: Option 1
        value: 100
        correct: true
      - label: Option 2
        value: 200
        correct: true
```
All options are correct so I should receive points regardless of which one I pick, but the result is always 0 points.

I believe I've located the cause to the method `grade_radio`
https://github.com/apluslms/mooc-grader/blob/5b8b120453552f9b8a1a31e742ee14d240605054/access/types/forms.py#L742-L759

Where on line 752 the `if name == value` is performing a str to int comparison, so it is always false.
